version: "3"

services:
    heurly:
        container_name: test.heurly
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env
